name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install
      continue-on-error: true # Allow to proceed even if there are warnings

    - name: Check for outdated packages
      run: |
        npm audit
        npm outdated

    - name: Run Bot
      run: |
        node bot.js
      continue-on-error: true # Continue despite errors in bot execution

    - name: Complete Job
      run: echo "Job completed."
